"""second

Revision ID: 47aec562b449
Revises: 51350fc3e746
Create Date: 2023-12-06 01:33:33.549912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47aec562b449'
down_revision = '51350fc3e746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_name', sa.String(length=500), nullable=True))
        batch_op.create_index(batch_op.f('ix_tag_tag_name'), ['tag_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_tag_name'))
        batch_op.drop_column('tag_name')

    # ### end Alembic commands ###
